name: dotnet publish page

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions: write-all

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x
      - name: Install workload
        run: |
          dotnet workload install wasm-tools
          dotnet workload install wasm-experimental
      - name: Publish Server
        run: dotnet publish ./Web/Web.csproj -o publish
      - name: Upload artifact to pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: publish/wwwroot
      - name: deploy page
        id: deployment
        uses: actions/deploy-pages@v4